# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
Psi_LSMLE_Cpp <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LSMLE_Cpp`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

Psi_LSMLE_Jacobian_C <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LSMLE_Jacobian_C`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

La_Cpp <- function(mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd) {
    .Call(`_RobustBetaReg_La_Cpp`, mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd)
}

Psi_LMDPDE_Cpp <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LMDPDE_Cpp`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

Psi_LMDPDE_Jacobian_C <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LMDPDE_Jacobian_C`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
OpenMPTest <- function(numThrd) {
    .Call(`_RobustBetaReg_OpenMPTest`, numThrd)
}

