# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
Psi_LSMLE_Cpp <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LSMLE_Cpp`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
L_alpha <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_L_alpha`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

Psi_LSMLE_Jacobian_C <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LSMLE_Jacobian_C`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

p_LSMLE_Cpp <- function(y_star, mu, phi, mu_0, phi_0, alpha, Kx, Kz) {
    .Call(`_RobustBetaReg_p_LSMLE_Cpp`, y_star, mu, phi, mu_0, phi_0, alpha, Kx, Kz)
}

dp_LSMLE_Cpp <- function(y_star, mu, phi, mu_0, phi_0, alpha, Kx, Kz) {
    .Call(`_RobustBetaReg_dp_LSMLE_Cpp`, y_star, mu, phi, mu_0, phi_0, alpha, Kx, Kz)
}

La_Cpp <- function(mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd) {
    .Call(`_RobustBetaReg_La_Cpp`, mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd)
}

La_CppB <- function(p0, y0, mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd) {
    .Call(`_RobustBetaReg_La_CppB`, p0, y0, mu, phi, mu_0, phi_0, alpha, Kx, Kz, thrd)
}

Psi_LMDPDE_Cpp <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LMDPDE_Cpp`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
D_alpha <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_D_alpha`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

Psi_LMDPDE_Jacobian_C <- function(Theta, y, X, Z, alpha, link_mu, link_phi) {
    .Call(`_RobustBetaReg_Psi_LMDPDE_Jacobian_C`, Theta, y, X, Z, alpha, link_mu, link_phi)
}

SQV_Cpp <- function(zq, n, p) {
    .Call(`_RobustBetaReg_SQV_Cpp`, zq, n, p)
}

#' @useDynLib RobustBetaReg, .registration=TRUE
#' @importFrom Rcpp evalCpp
OpenMPTest <- function(numThrd) {
    .Call(`_RobustBetaReg_OpenMPTest`, numThrd)
}

