# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RobustBetaReg_rcpp_hello_world`)
}

timesTwo <- function(x) {
    .Call(`_RobustBetaReg_timesTwo`, x)
}

times4 <- function(x) {
    .Call(`_RobustBetaReg_times4`, x)
}

a19 <- function(x) {
    .Call(`_RobustBetaReg_a19`, x)
}

a20 <- function(x) {
    .Call(`_RobustBetaReg_a20`, x)
}

eta <- function(x, theta) {
    .Call(`_RobustBetaReg_eta`, x, theta)
}

degbeta_C <- function(y_star, mu, phi) {
    .Call(`_RobustBetaReg_degbeta_C`, y_star, mu, phi)
}

